koGrid = {
    rowHeight: 28,
    headerRowHeight: 26,
    canSelectRows: true,
    columnWidth: 100,
    disableTextSelection: true,
    displaySelectionCheckbox: true,
    enableColumnResize: true,
    enableRowReordering: false,
    enableSorting: ko.observable(true),
    filterOptions: {
        filterText: ko.observable(""),
        useExternalFilter: false,
    },
    footerRowHeight: 55,
    footerVisible: true,
    groups: [],
    headerRowTemplate: undefined,
    jqueryUIDraggable: false,
    jqueryUITheme: false,
    keepLastSelected: true,
    maintainColumnRatios: undefined,
    multiSelect: true,
    plugins: [],
    rowTemplate: undefined,
    selectWithCheckboxOnly: false,
    showColumnMenu: true,
    showFilter: true,
    showGroupPanel: false,
    sortInfo: undefined,
    tabIndex: -1,
    useExternalSorting: false,
    watchDataItems: false,
    enablePaging: true
}