function mainVm(){
  var self = this;
  this.myData = ko.observableArray([
    {a:"a",b:"b",c:"c",d:"d",e:"eeeeeeee eeeeee eeeeeee eeeeee",f:"ffff f f f fff f f",g: "asdf", h: "Moroni Moroni Moroni Moroni Moroni", i: 50},
    {a:"a",b:"b",c:"c",d:"d",e:"eeeeeeee eeeeee eeeeeee eeeeee",f:"ffff f f f fff f f",g: "asdf", h: "Tiancum Tiancum Tiancum Tiancum Tiancum", i: 43},
    {a:"a",b:"b",c:"c",d:"d",e:"eeeeeeee eeeeee eeeeeee eeeeee",f:"ffff f f f fff f f",g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:"eeeeeeee eeeeee eeeeeee eeeeee",f:"ffff f f f fff f f",g: "asdf", h: "Nephi", i: 29},
    {a:"a",b:"b",c:"c",d:"d",e:"eeeeeeee eeeeee eeeeeee eeeeee",f:"ffff f f f fff f f",g: "asdf", h: "Tiancum Tiancum Tiancum Tiancum Tiancum", i: 43},
    {a:"a",b:"b",c:"c",d:"d",e:"eeeeeeee eeeeee eeeeeee eeeeee",f:"ffff f f f fff f f",g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:"eeeeeeee eeeeee eeeeeee eeeeee",f:"ffff f f f fff f f",g: "asdf", h: "Nephi", i: 29},
    {a:"a",b:"b",c:"c",d:"d",e:"eeeeeeee eeeeee eeeeeee eeeeee",f:"ffff f f f fff f f",g: "asdf", h: "Enos", i: 34},
    {a:"a",b:"b",c:"c",d:"d",e:'eee eee eee eee eee eee ee',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27},
    {a:"a",b:"b",c:"c",d:"d",e:'e',f:'f',g: "asdf", h: "Jacob", i: 27}
  ]);
}
ko.applyBindings(new mainVm());
